services:
  webapp:
    hostname: webapp
    build:
      context: webapp
      dockerfile: dev.Dockerfile
    command:
      - sh
      - -c
      - /usr/sbin/php-fpm82 && nginx -g 'daemon off;'
    volumes:
      - "./webapp:/srv/http"
    ports:
      - "8080:80"
  wg:
    environment:
      APP_URL: 'webapp'
      TOKEN: 'RgV7mpSkRIDI13p9emd01AAOeAqwWQ5rw0KKdObKAfTfraJbfGz6Dtx'
    build:
      context: wg
    privileged: true

