---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-manager.fullname" . }}-webapp
  labels:
    {{- include "wg-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webapp.service.type }}
  ports:
    - port: {{ .Values.webapp.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    name: {{ include "wg-manager.fullname" . }}-webapp
{{ if .Values.wg.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wg-manager.fullname" . }}-wg
  labels:
    {{- include "wg-manager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wg.service.type }}
  ports:
    {{- range .Values.wg.ports }}
    - port: {{ . }}
      targetPort: port{{.}}
      protocol: UDP
      name: port{{.}}
    {{- end }}

  selector:
    name: {{ include "wg-manager.fullname" . }}-wg
{{ end }}