webapp:
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  secret: webapp-secret
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: "public"
    annotations: 
      cert-manager.io/cluster-issuer: "letsencrypt"
    hosts:
      - host: example.com
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: 
     - secretName: test-tls
       hosts:
         - example.com
wg:
  enabled: true
  podLabels: {}
  podAnnotations: {}
  service:
    type: NodePort
    ports:
      - 30001
      - 30002
      - 30003
      - 30004
      - 30005
      - 30006
      - 30007
      - 30008
      - 30009
      - 30010
  nodeSelector: {}
  secret: wg-secret

