name: Generate Image for auto-deploy

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker meta main
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}/webapp
          tags: |
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push main Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./webapp
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
